version: '3'
services:

  db:
    image: postgres:9.6
    environment:
      - POSTGRES_PASSWORD=carbonfiber
      - POSTGRES_USER=sfusion
    volumes:
      - db-data:/var/lib/postgresql

  api:
    build: ./api
    image: sfusion:latest
    restart: always
    ports:
      - "8888"

  web:
    build: ./web
    image: sfweb:latest
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api


volumes:
  db-data: