version: '3'
services:


  api:
    build: ./api
    image: sfusion:latest
    restart: always
    ports:
      - "8888"

  web:
    build: ./web
    image: sfweb:latest
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api





